package com.coditory.distributed.lock.reactive

import com.coditory.distributed.lock.tests.AcquireLockMultipleTimesSpec
import com.coditory.distributed.lock.tests.AcquireLockSpec
import com.coditory.distributed.lock.tests.InfiniteAcquireLockSpec
import com.coditory.distributed.lock.tests.ReleaseLockSpec

class ReactiveMongoReleaseLockSpec extends ReleaseLockSpec implements UsesReactiveMongoDistributedLocks {}

class ReactiveMongoAcquireLockSpec extends AcquireLockSpec implements UsesReactiveMongoDistributedLocks {}

class ReactiveMongoAcquireLockMultipleTimesSpec extends AcquireLockMultipleTimesSpec implements UsesReactiveMongoDistributedLocks {}

class ReactiveMongoInfiniteAcquireLockSpec extends InfiniteAcquireLockSpec implements UsesReactiveMongoDistributedLocks {}
