package com.coditory.distributed.lock.reactive

import com.coditory.distributed.lock.tests.AcquireLockMultipleTimesSpec
import com.coditory.distributed.lock.tests.AcquireLockSpec
import com.coditory.distributed.lock.tests.InfiniteAcquireLockSpec
import com.coditory.distributed.lock.tests.ReleaseLockSpec

class ReactorMongoReleaseLockSpec extends ReleaseLockSpec implements UsesReactorMongoDistributedLocks {}

class ReactorMongoAcquireLockSpec extends AcquireLockSpec implements UsesReactorMongoDistributedLocks {}

class ReactorMongoAcquireLockMultipleTimesSpec extends AcquireLockMultipleTimesSpec implements UsesReactorMongoDistributedLocks {}

class ReactorMongoInfiniteAcquireLockSpec extends InfiniteAcquireLockSpec implements UsesReactorMongoDistributedLocks {}
